dist: bionic

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - ./install.sh

# Don't waste time cloning previous commits.
# No git stuff is tested anyway.
git:
  depth: 1

branches:
  only:
  - master
  - dev

script:
  - pytest -v --cov=spoonerize --cov-report=xml --cov-report=term-missing
  - make -C docs html
